<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Articulo extends Model
{
	protected $table = 'articulo';
	public $timestamps = false;

	protected $casts = [
		'MPENDING' => 'float',
		'MPENDSAL' => 'float',
		'MPESO' => 'float',
		'MFACRUM' => 'float',
		'MSTOCKINI' => 'float',
		'MCOSTOINI' => 'float',
		'MCOSTO' => 'float',
		'MCOSULCO' => 'float',
		'MSTOCK' => 'float',
		'MSTOCKSAL' => 'float',
		'MSTOCKENT' => 'float',
		'MSTOCKMIN' => 'float',
		'MSTOCKMAX' => 'float',
		'MSTCOMPR' => 'float',
		'MPVENTA' => 'float',
		'MFACUTIL' => 'float',
		'MFACUT1' => 'float',
		'MFACUTSG' => 'float',
		'MVALREPOS' => 'float',
		'MPORDCTO' => 'float',
		'MPVENTA1' => 'float',
		'MPVTAS01' => 'float',
		'MPVTAS02' => 'float',
		'MPVTAS03' => 'float',
		'MPVTAS04' => 'float',
		'MPVTAS05' => 'float',
		'MFACUT01' => 'float',
		'MFACUT02' => 'float',
		'MFACUT03' => 'float',
		'MTIEMPO' => 'float',
		'MTIEACA' => 'float',
		'MPNETO' => 'float',
		'MPBRUTO' => 'float',
		'MPVTAS06' => 'float',
		'MPVTAS07' => 'float',
		'MPVTAS08' => 'float',
		'MPVTAS09' => 'float',
		'MPVTAS10' => 'float',
		'MPVTAS11' => 'float',
		'MPVTAS12' => 'float',
		'MPVTAS13' => 'float',
		'MPVTAS14' => 'float',
		'MPVTAS15' => 'float',
		'MPVTAS16' => 'float',
		'MPVTAS17' => 'float',
		'MPVTAS18' => 'float',
		'MPVTAS19' => 'float',
		'MPVTAS20' => 'float',
		'MPOR_ISC' => 'float',
		'MPOR_COMI' => 'float',
		'MROTA_EST' => 'float',
		'MDIM_INT1' => 'float',
		'MDIM_EXT1' => 'float',
		'MDIM_ALT1' => 'float',
		'MDIM_INT2' => 'float',
		'MDIM_INT3' => 'float',
		'MDIM_EXT2' => 'float',
		'MDIM_EXT3' => 'float',
		'MDIM_ALT2' => 'float',
		'MDIM_ALT3' => 'float',
		'MPLNCH_ESP' => 'float',
		'MPLNCH_CAN' => 'float',
		'MPASOSMTRZ' => 'float',
		'MCASCO_PES' => 'float',
		'MCASCO_ESP' => 'float',
		'MTAPA_PES' => 'float',
		'MTAPA_ESP' => 'float',
		'MRESOR_PES' => 'float',
		'MRESOR_ESP' => 'float',
		'MRESOR_LON' => 'float',
		'MRESOR_DIA' => 'float',
		'MCAUCHCR_W' => 'float',
		'MCAUCHSR_W' => 'float',
		'MUNDENV1' => 'float',
		'MUNDENV2' => 'float',
		'MPNETESC' => 'float',
		'MNIVEXPM' => 'float',
		'MBOLPESO' => 'float',
		'MBOLFCB' => 'float',
		'MUNDENV3' => 'float',
		'MUNDENV4' => 'float',
		'MFECULSA' => 'datetime',
		'MFECULIN' => 'datetime',
		'MFECULCO' => 'datetime',
		'MFECUVEN' => 'datetime',
		'MFECREGI' => 'datetime',
		'MFCHVALOF' => 'datetime',
		'MFECUACT' => 'datetime',
		'M_CORECTI' => 'datetime',
		'MFCH_MEMO' => 'datetime',
		'MFECCADU' => 'datetime',
	];

	protected $fillable = [
		'MCODART',
		'MDESCRIP',
		'MABREVI',
		'MCODTPT',
		'MCODFAM',
		'MCODCLA',
		'MCODEQUI',
		'MUNIDAD',
		'MINDCTO',
		'MINDDEC',
		'MINDPRD',
		'MINDSPRD',
		'MINDCADU',
		'MINDSERIE',
		'MINDLOTE',
		'MCTAARANC',
		'MFECULSA',
		'MFECULIN',
		'MFECULCO',
		'MFECUVEN',
		'MPENDING',
		'MPENDSAL',
		'MCODACA',
		'MCODLAD',
		'MCODNOR',
		'MCODFOR',
		'MCOMI',
		'MINSUMO',
		'MPESO',
		'MFACRUM',
		'MESTADO',
		'MSTOCKINI',
		'MGRUPO',
		'MCOSTOINI',
		'MCOSTO',
		'MCOSULCO',
		'MCODALT',
		'MCODCOL',
		'MSTOCK',
		'MSTOCKSAL',
		'MSTOCKENT',
		'MCTAVEN',
		'MCTADCTO',
		'MSTOCKMIN',
		'MSTOCKMAX',
		'MSTCOMPR',
		'MPVENTA',
		'MPROCEDE',
		'MCTACTB',
		'MFACUTIL',
		'MFACUT1',
		'MFACUTSG',
		'MFECREGI',
		'MMDAULCO',
		'MVALREPOS',
		'MLINSER',
		'MPORDCTO',
		'MOFERTA',
		'MFCHVALOF',
		'MPVENTA1',
		'MPVTAS01',
		'MPVTAS02',
		'MPVTAS03',
		'MPVTAS04',
		'MPVTAS05',
		'MFACUT01',
		'MFACUT02',
		'MFACUT03',
		'MTIEMPO',
		'MCODFMP',
		'MCODPST',
		'MCODBOC',
		'MCAVI',
		'MCODPRO',
		'MCODCLI',
		'MTIEACA',
		'MCODANT',
		'MOBSERV',
		'MCODGNR',
		'MCODCLD',
		'MCODTEN',
		'MCODDESP',
		'MCODUMED',
		'MPNETO',
		'MPBRUTO',
		'MCODUSER',
		'MFECUACT',
		'MHORUACT',
		'MPVTAS06',
		'MPVTAS07',
		'MPVTAS08',
		'MPVTAS09',
		'MPVTAS10',
		'MPVTAS11',
		'MPVTAS12',
		'MPVTAS13',
		'MPVTAS14',
		'MPVTAS15',
		'MPVTAS16',
		'MPVTAS17',
		'MPVTAS18',
		'MPVTAS19',
		'MPVTAS20',
		'MAFE_IGV',
		'MPOR_ISC',
		'MPOR_COMI',
		'MIND_ENS',
		'MROTA_EST',
		'MDIM_INT1',
		'MDIM_EXT1',
		'MDIM_ALT1',
		'MDIM_INT2',
		'MDIM_INT3',
		'MDIM_EXT2',
		'MDIM_EXT3',
		'MDIM_ALT2',
		'MDIM_ALT3',
		'MNRO_FAB',
		'MGI_STRIA',
		'MINDPROMO',
		'MCOD_ORI',
		'MDISENO',
		'MPLNCH_ESP',
		'MPLNCH_CAN',
		'MPASOSMTRZ',
		'MCASCO_PES',
		'MCASCO_ESP',
		'MTAPA_PES',
		'MTAPA_ESP',
		'MRESOR_PES',
		'MRESOR_ESP',
		'MRESOR_LON',
		'MRESOR_DIA',
		'MCAUCHCR_W',
		'MCAUCHSR_W',
		'MN_CORECTI',
		'MF_CORECTI',
		'MNRO_MEMO',
		'MFCH_MEMO',
		'MNOMB_PLIS',
		'MENVASE1',
		'MUNDENV1',
		'MENVASE2',
		'MUNDENV2',
		'MFECCADU',
		'MPNETESC',
		'MNIVEXPM',
		'MBOLIND',
		'MBOLDES',
		'MBOLUME',
		'MBOLPESO',
		'MBOLFCB',
		'MCODUME1',
		'MCODUME2',
		'MCODUME3',
		'MENVASE3',
		'MUNDENV3',
		'MCODUME4',
		'MENVASE4',
		'MUNDENV4',
		'MINDOBSQ',
		'MCODTIES',
		'MRTACION',
		'MAFEPERC',
		'MCODSCLA',
		'MCODVAR01',
		'MCODVAR02',
		'MDES_ADI',
		'MCODDCTOP',
		'MCODDCTOE',
	];

	public function getCorrectPrice($mcodcadi) {
		$price = false;
		switch ($mcodcadi) {
			case '01':
				$price = $this->MPVTAS05;
				break;
			  case '02':
				$price = $this->MPVTAS06;
				break;
			  case '03':
				$price = $this->MPVTAS07;
				break;
			  default:
				$price = $this->MPVTAS08;
		}
		if ($price == 0.0) {
			$price = $this->MPVTAS09 != null ? $this->MPVTAS09 : $this->MPVTAS10;
		}

    	return number_format(floatval($price), 4);
	}
}
